### ISSUE TITLE
Menu Scrolling Isn't Working on iPhone Xs

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community-portal#435] opened 2020-09-07 18:17 UTC
**Describe the bug**
I can't scroll the menu on my iPhone Xs on Safari on staging. Haven't tested on other browsers. 

**To Reproduce**
1. Go to any page on mobile on iphone.
2. Click on menu.
3. Try to scroll down.
4. It won't scroll.

**Expected behavior**
I would expect it to scroll when there is enough content to be scrollable. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  iPhone Xs
 - OS: iOS
 - Browser Safari
 - Version Latest update.

**Additional context**

**Comment by TomDeMichele** [comment] 2020-09-07 18:36
Actually seems to be fixed with the latest build. Will see if I can reproduce.

**Comment by TomDeMichele** [comment] 2020-09-07 18:40
Actually, false alarm. So I thought it happened all the time, but it happens intermittently. I seem to be able to get it to happen when I click from one page to another on mobile. For example, I clicked from https://community-portal-staging.makerfoundation.com/en/learn/governance to https://community-portal-staging.makerfoundation.com/en/learn/governance/on-chain-gov. I think it was happening often enough to where I thought it was every page, but it was not.

**Comment by TomDeMichele** [comment] 2020-09-07 18:41
Also, only seems to happen the first time the menu is clicked on. If I close the menu and then click it again it will scroll.

**Comment by MaximumCrash** [comment] 2020-09-08 11:40
Duplicate of #308. Is going to be fixed as part of #429

**Closed as completed** 2020-09-08 19:09 UTC
Labels: bug
