### ISSUE TITLE
Learn and Work With Us Chocolate Boxes Don't Align on Mobile (Safari)

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community-portal#451] opened 2020-09-15 18:19 UTC
**Describe the bug**
The chocolate boxes don't align on mobile on the Learn and Work with us pages where there is 3 boxes. Works on funding where there is 2.

**To Reproduce**
1. Go to Work With Us on mobile on Safari.

**Expected behavior**
They should be stacking either 1-by-1 or 2-by-2 and not breaking the bounds of the underlying container.

**Screenshots**
![image0](https://user-images.githubusercontent.com/54551507/93248875-50e1c980-f745-11ea-8c03-a2a4a0b5ba7e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: IPhone Sx
 - Browser Safari

**Additional context**

**Comment by MaximumCrash** [comment] 2020-09-17 23:25
Duplicate of #460

**Comment by MaximumCrash** [comment] 2020-09-23 22:23
Closed by #474

**Closed as completed by MaximumCrash** 2020-09-23 22:23 UTC
Labels: bug, mobile
